Repository compsci-adl/duckbot, pull requests merged in 2024-09, with the labels that each got.

#52 build(ci) Use Github runner
  .github/workflows/production.yml
  Dockerfile
Labels: ci

#50 feat: Implement Google Gemini API
  .example.env
  .github/workflows/production.yml
  poetry.lock
  pyproject.toml
  src/commands/faq.py
  src/commands/gemini.py
  src/constants/colours.py
  src/data/duckbot_train_data.csv
  src/main.py
Labels: enhancement, dependencies

#61 feat(chat): Add Rate Limit
  .example.env
  .github/workflows/production.yml
  src/commands/gemini.py
  src/main.py
Labels: enhancement
