Repository compsci-adl/duckbot, pull requests merged in 2024-07, with the labels that each got.

#16 docs: Update readme and load environment variables properly
  README.md
  src/main.py
Labels: documentation

#18 fix: Make lint action only check code formatting
  .github/workflows/lint.yml
  pyproject.toml
Labels: ci

#19 feat: Implement faq group with rsp and cpc commands
  src/commands/faq.py
Labels: enhancement

#14 Skullboard
  .example.env
  .github/workflows/production.yml
  poetry.lock
  src/commands/skullboard.py
  src/constants/colours.py
  src/main.py
Labels: enhancement

#17 feat: Add Friday Night Games date command
  src/commands/faq.py
Labels: enhancement
